ProASPNETCore3/Chapter30/UsingFilters/UsingFilters/Controllers/ResourceFilterController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UsingFilters.CustomFilters;
using UsingFilters.Model;
//----------------------------------------------------------------------------------------------------------------------
namespace UsingFilters.Controllers
{
//----------------------------------------------------------------------------------------------------------------------
	public sealed class ResourceFilterController : Controller
	{
//----------------------------------------------------------------------------------------------------------------------
		[CSynchronousResource]
		public ViewResult Synchronous()
		{
			CResultMessageWithTime								Model=new CResultMessageWithTime("ACTION METHOD is EXECUTED !",DateTime.Now.ToString());
			ViewResult											Result=View("ResultMessageChachedSynchronous",Model);

			return(Result);
		}
//----------------------------------------------------------------------------------------------------------------------
		[CAsynchronousResource]
		public ViewResult Asynchronous()
		{
			CResultMessageWithTime								Model=new CResultMessageWithTime("ACTION METHOD is EXECUTED !",DateTime.Now.ToString());
			ViewResult											Result=View("ResultMessageChachedAsynchronous",Model);

			return(Result);
		}
//----------------------------------------------------------------------------------------------------------------------
	}
//----------------------------------------------------------------------------------------------------------------------
}
//----------------------------------------------------------------------------------------------------------------------

ProASPNETCore3/Chapter30/UsingFilters/UsingFilters/Views/Shared/ResultData.cshtml
@model CResultData

@{
	Layout=null;
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="~/StaticFiles/Styles/Styles.css" />
	<link rel="stylesheet" href="~/StaticFiles/ClientLibraries/Bootstrap/css/bootstrap.css" />
	<title>Result Data</title>
</head>
<body>
	<div class="OUTER_BOX">
		<table class="table table-bordered table-striped">
			<tr>
				<th>Url:</th>

				<th>
					Value:
				</th>
			</tr>

			@foreach(KeyValuePair<string,string> KeyValue in @Model.Data)
			{
				<tr>
					<th>
						@KeyValue.Key
					</th>
						
					<td>
						[@KeyValue.Value] !
					</td>
				</tr>
			}
		</table>
	</div>
</body>
</html>

ProASPNETCore3/Chapter30/UsingFilters/UsingFilters/Views/Shared/ResultMessage.cshtml
@model CResultMessage

@{
	Layout=null;
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="~/StaticFiles/Styles/Styles.css" />
	<link rel="stylesheet" href="~/StaticFiles/ClientLibraries/Bootstrap/css/bootstrap.css" />
	<title>Result Message</title>
</head>
<body>
	<div class="OUTER_BOX">
		Model Data: [@Model.Message] !
	</div>
</body>
</html>

ProASPNETCore3/Chapter30/UsingFilters/UsingFilters/Views/Shared/ResultMessageChachedAsynchronous.cshtml
@model CResultMessageWithTime

@{
	Layout=null;
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="~/StaticFiles/Styles/Styles.css" />
	<link rel="stylesheet" href="~/StaticFiles/ClientLibraries/Bootstrap/css/bootstrap.css" />
	<title>Result Message with Time</title>
</head>
<body>
	<div class="OUTER_BOX">
		Model Data: [@Model.Message] !
		<br/>
		Time: [@Model.Time] !
		<br/>
		Go to [<a asp-controller="ResourceFilter" asp-action="Asynchronous">Reload PAGE !</a>] !
	</div>
</body>
</html>

ProASPNETCore3/Chapter30/UsingFilters/UsingFilters/Views/Shared/ResultMessageChachedSynchronous.cshtml
@model CResultMessageWithTime

@{
	Layout=null;
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="~/StaticFiles/Styles/Styles.css" />
	<link rel="stylesheet" href="~/StaticFiles/ClientLibraries/Bootstrap/css/bootstrap.css" />
	<title>Result Message with Time</title>
</head>
<body>
	<div class="OUTER_BOX">
		Model Data: [@Model.Message] !
		<br/>
		Time: [@Model.Time] !
		<br/>
		Go to [<a asp-controller="ResourceFilter" asp-action="Synchronous">Reload PAGE !</a>] !
	</div>
</body>
</html>

ProASPNETCore3/Chapter30/UsingFilters/UsingFilters/Views/Shared/ResultMessageWithCounter.cshtml
@model CResultMessageWithCounter

@{
	Layout=null;
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="~/StaticFiles/Styles/Styles.css" />
	<link rel="stylesheet" href="~/StaticFiles/ClientLibraries/Bootstrap/css/bootstrap.css" />
	<title>Result Message with Counter</title>
</head>
<body>
	<div class="OUTER_BOX">
		Model Data: [@Model.Message] !
		<br/>
		Counter: [@Model.Counter] !
	</div>
</body>
</html>

ProASPNETCore3/Chapter30/UsingFilters/UsingFilters/Views/Shared/ResultMessageWithExecutionTime.cshtml
@model CResultMessageWithExecutionTime

@{
	Layout=null;
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="~/StaticFiles/Styles/Styles.css" />
	<link rel="stylesheet" href="~/StaticFiles/ClientLibraries/Bootstrap/css/bootstrap.css" />
	<title>Result Message with Execution Time</title>
</head>
<body>
	<div class="OUTER_BOX">
		Model Data: [@Model.Message] !
		<br/>
		Execution Time: [@Model.ExecutionTime] !
	</div>
</body>
</html>

ProASPNETCore3/Chapter30/UsingFilters/UsingFilters/Views/Shared/ResultMessageWithTime.cshtml
@model CResultMessageWithTime

@{
	Layout=null;
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="~/StaticFiles/Styles/Styles.css" />
	<link rel="stylesheet" href="~/StaticFiles/ClientLibraries/Bootstrap/css/bootstrap.css" />
	<title>Result Message with Time</title>
</head>
<body>
	<div class="OUTER_BOX">
		Model Data: [@Model.Message] !
		<br/>
		Time: [@Model.Time] !
	</div>
</body>
</html>

ProASPNETCore3/Chapter30/UsingFilters/UsingFilters/Views/Shared/Unauthorized.cshtml
@model CResultMessage

@{
	Layout=null;
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="~/StaticFiles/Styles/Styles.css" />
	<link rel="stylesheet" href="~/StaticFiles/ClientLibraries/Bootstrap/css/bootstrap.css" />
	<title>Unauthorized</title>
</head>
<body>
	<div class="OUTER_BOX">
		ACTION METHOD [@Model.Message] is UNAUTHORIZED !
	</div>
</body>
</html>