ProASPNETCore3/Chapter24/ViewComponents/ViewComponents/Controllers/ContextViewComponentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
//----------------------------------------------------------------------------------------------------------------------
namespace ViewComponents.Controllers
{
//----------------------------------------------------------------------------------------------------------------------
	public class ContextViewComponentsController : Controller
	{
//----------------------------------------------------------------------------------------------------------------------
		public IActionResult MyActionMethod()
		{
			ViewResult											Result=View("UsingViewComponentContext");

			return(Result);
		}
//----------------------------------------------------------------------------------------------------------------------
	}
//----------------------------------------------------------------------------------------------------------------------
}
//----------------------------------------------------------------------------------------------------------------------

ProASPNETCore3/Chapter24/ViewComponents/ViewComponents/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
//----------------------------------------------------------------------------------------------------------------------
namespace ViewComponents.Controllers
{
//----------------------------------------------------------------------------------------------------------------------
	public sealed class HomeController : Controller
	{
//----------------------------------------------------------------------------------------------------------------------
		public ViewResult Index()
		{
			return(View());
		}
//----------------------------------------------------------------------------------------------------------------------
	}
//----------------------------------------------------------------------------------------------------------------------
}
//----------------------------------------------------------------------------------------------------------------------

ProASPNETCore3/Chapter24/ViewComponents/ViewComponents/Controllers/HybridParentViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
//----------------------------------------------------------------------------------------------------------------------
namespace ViewComponents.Controllers
{
//----------------------------------------------------------------------------------------------------------------------
	public class HybridParentViewController : Controller
	{
//----------------------------------------------------------------------------------------------------------------------
		public IActionResult MyActionMethod()
		{
			ViewResult											Result=View("HybridView");

			return(Result);
		}
//----------------------------------------------------------------------------------------------------------------------
	}
//----------------------------------------------------------------------------------------------------------------------
}
//----------------------------------------------------------------------------------------------------------------------

ProASPNETCore3/Chapter24/ViewComponents/ViewComponents/Controllers/PocoViewComponentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
//----------------------------------------------------------------------------------------------------------------------
namespace ViewComponents.Controllers
{
//----------------------------------------------------------------------------------------------------------------------
	public class PocoViewComponentsController : Controller
	{
//----------------------------------------------------------------------------------------------------------------------
		public IActionResult MyActionMethod1()
		{
			ViewResult											Result=View("MyPoco1View");

			return(Result);
		}
//----------------------------------------------------------------------------------------------------------------------
		public IActionResult MyActionMethod2()
		{
			ViewResult											Result=View("MyPoco2View");

			return(Result);
		}
//----------------------------------------------------------------------------------------------------------------------
	}
//----------------------------------------------------------------------------------------------------------------------
}
//----------------------------------------------------------------------------------------------------------------------

ProASPNETCore3/Chapter24/ViewComponents/ViewComponents/Controllers/UsingViewComponentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ViewComponents.Model;
//----------------------------------------------------------------------------------------------------------------------
namespace ViewComponents.Controllers
{
//----------------------------------------------------------------------------------------------------------------------
	public class UsingViewComponentsController : Controller
	{
//----------------------------------------------------------------------------------------------------------------------
		public IActionResult UsingViaInvokeMethod()
		{
			ViewResult											Result=View("UsingViaInvokeMethod");

			return(Result);
		}
//----------------------------------------------------------------------------------------------------------------------
		public IActionResult UsingViaTagHelper()
		{
			ViewResult											Result=View("UsingViaTagHelper");

			return(Result);
		}
//----------------------------------------------------------------------------------------------------------------------
	}
//----------------------------------------------------------------------------------------------------------------------
}
//----------------------------------------------------------------------------------------------------------------------

ProASPNETCore3/Chapter24/ViewComponents/ViewComponents/Views/Home/Index.cshtml
@{
	Layout=null;
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="~/StaticFiles/Styles/Styles.css" />
	<title>Index</title>
</head>
<body>
	<div class="OUTER_BOX">
		<div class="INNER_BOX">
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory vracia STRING. -->
			Go to [<a asp-controller="PocoViewComponents" asp-action="MyActionMethod1">Show POCO VIEW COMPONENT returning STRING !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory vracia PARTIAL VIEW. -->
			Go to [<a asp-controller="PocoViewComponents" asp-action="MyActionMethod2">Show POCO VIEW COMPONENT returning PARTIAL VIEW !</a>] !
		</div>

		<div class="INNER_BOX">
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory vracia STRING. -->
			Go to [<a asp-controller="DerivedViewComponents" asp-action="MyActionMethod1">Show DERIVED VIEW COMPONENT returning STRING !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory vracia PARTIAL VIEW. -->
			Go to [<a asp-controller="DerivedViewComponents" asp-action="MyActionMethod2">Show DERIVED VIEW COMPONENT returning PARTIAL VIEW !</a>] !
		</div>

		<div class="INNER_BOX">
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory je pouzity cez METHOD [InvokeAsync()]. -->
			Go to [<a asp-controller="UsingViewComponents" asp-action="UsingViaInvokeMethod">Show VIEW COMPONENT used by METHOD InvokeAsync() !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory je pouzity cez TAG HELPER. -->
			Go to [<a asp-controller="UsingViewComponents" asp-action="UsingViaTagHelper">Show VIEW COMPONENT used by TAG HELPER !</a>] !
		</div>

		<div class="INNER_BOX">
			<!-- !!! Zobrazi sa RAZOR PAGE, ktory pouziva VIEW COMPONENT. -->
			Go to [<a href="http://localhost:50000/RazorPageUsingViewComponent">Show RAZOR PAGE using VIEW COMPONENT !</a>] !
		</div>

		<div class="INNER_BOX">
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory vracia PARTIAL VIEW. -->
			Go to [<a asp-controller="ReturnValueViewComponents" asp-action="ReturnPartialView1">Show VIEW COMPONENT returning PARTIAL VIEW !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory vracia PARTIAL VIEW cez FULL PATH. -->
			Go to [<a asp-controller="ReturnValueViewComponents" asp-action="ReturnPartialView2">Show VIEW COMPONENT returning PARTIAL VIEW using FULL PATH !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory vracia PARTIAL VIEW umiestneny v DIRECTORY [Pages/Shared/Components/ReturnValuePartialView3]. -->
			Go to [<a asp-controller="ReturnValueViewComponents" asp-action="ReturnPartialView3">Show VIEW COMPONENT returning PARTIAL VIEW in DIRECTORY [Pages/Shared/Components/ReturnValuePartialView3] !</a>] !
			<br/>
			<!-- !!! Zobrazi sa RAZOR PAGE s VIEW COMPONENT, ktory vracia PARTIAL VIEW umiestneny v DIRECTORY [Views/Shared/Components/ReturnValuePartialView4]. -->
			Go to [<a href="http://localhost:50000/ReturnPartialView4">Show VIEW COMPONENT returning PARTIAL VIEW in DIRECTORY [Views/Shared/Components/ReturnValuePartialView4] !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory vracia ENCODED HTML STRING. -->
			Go to [<a asp-controller="ReturnValueViewComponents" asp-action="ReturnEncodedHtmlString">Show VIEW COMPONENT returning ENCODED HTML STRING !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory vracia NOT ENCODED HTML STRING. -->
			Go to [<a asp-controller="ReturnValueViewComponents" asp-action="ReturnNotEncodedHtmlString">Show VIEW COMPONENT returning NOT ENCODED HTML STRING !</a>] !
		</div>

		<div class="INNER_BOX">
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory pouziva PROPERTIES VIEW COMPONENT CONTEXT. -->
			Go to [<a asp-controller="ContextViewComponents" asp-action="MyActionMethod">Show VIEW COMPONENT using VIEW COMPONENT CONTEXT !</a>] !
		</div>

		<div class="INNER_BOX">
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory zobrazi zoznam NAMES. Na zobrazenie VIEW COMPONENT sa pouziva METHOD [InvokeAsync()]. -->
			Go to [<a asp-controller="ParametersViewComponents" asp-action="ActionMethodNamesInPlainTextUsingInvoke">Show NAMES in PLAIN TEXT using METHOD [InvokeAsync()] !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory zobrazi zoznam NAMES v BOLD TEXT. Na zobrazenie VIEW COMPONENT sa pouziva METHOD [InvokeAsync()]. -->
			Go to [<a asp-controller="ParametersViewComponents" asp-action="ActionMethodNamesInBoldTextUsingInvoke">Show NAMES in BOLD TEXT using METHOD [InvokeAsync()] !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory zobrazi zoznam NAMES v ITALICS TEXT. Na zobrazenie VIEW COMPONENT sa pouziva METHOD [InvokeAsync()]. -->
			Go to [<a asp-controller="ParametersViewComponents" asp-action="ActionMethodNamesInItalicsTextUsingInvoke">Show NAMES in ITALICS TEXT using METHOD [InvokeAsync()] !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory zobrazi zoznam NAMES. Na zobrazenie VIEW COMPONENT sa pouziva TAG HELPER. -->
			Go to [<a asp-controller="ParametersViewComponents" asp-action="ActionMethodNamesInPlainTextUsingTagHelper">Show NAMES in PLAIN TEXT using TAG HELPER !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory zobrazi zoznam NAMES v BOLD TEXT. Na zobrazenie VIEW COMPONENT sa pouziva TAG HELPER. -->
			Go to [<a asp-controller="ParametersViewComponents" asp-action="ActionMethodNamesInBoldTextUsingTagHelper">Show NAMES in BOLD TEXT using TAG HELPER !</a>] !
			<br/>
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory zobrazi zoznam NAMES v ITALICS TEXT.  Na zobrazenie VIEW COMPONENT sa pouziva TAG HELPER. -->
			Go to [<a asp-controller="ParametersViewComponents" asp-action="ActionMethodNamesInItalicsTextUsingTagHelper">Show NAMES in ITALICS TEXT using TAG HELPER !</a>] !
		</div>

		<div class="INNER_BOX">
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory pouziva ASYNCHRONOUS VERSION METHOD [Task<RETURN_TYPE> InvokeAsync()]. -->
			Go to [<a asp-controller="AsynchronousViewComponents" asp-action="MyActionMethod">Show ASYNCHRONOUS VIEW COMPONENT !</a>] !
		</div>

		<div class="INNER_BOX">
			<!-- !!! Zobrazi sa RAZOR PAGE, ktory pouziva RAZOR PAGE HYBRID VIEW COMPONENT. -->
			Go to [<a href="http://localhost:50000/TestRazorPageHybridVC">Show RAZOR PAGE using RAZOR PAGE HYBRID VIEW COMPONENT !</a>] !
			<br/>
			<!-- !!! Zobrazi sa RAZOR PAGE, ktory je zaroven HYBRID VIEW COMPONENT. -->
			Go to [<a href="http://localhost:50000/RazorPageHybridViewComponent">Show RAZOR PAGE written as HYBRID VIEW COMPONENT !</a>] !
		</div>

		<div class="INNER_BOX">
			<!-- !!! Zobrazi sa VIEW s VIEW COMPONENT, ktory je HYBRID VIEW COMPONENT a teda funguje zaroven aj ako CONTROLLER. -->
			Go to [<a asp-controller="HybridParentView" asp-action="MyActionMethod">Show HYBRID VIEW COMPONENT !</a>] !
		</div>
	</div>
</body>
</html>